Revert to 0ab68b2 to restore green build

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -3,9 +3,10 @@ name: CI
 on:
   push:
     branches: [main]
-  workflow_dispatch:
-
+    workflow_dispatch
+    
 jobs:
+
   echo-hello:
     runs-on: ubuntu-latest
     steps:
@@ -15,5 +16,10 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
+      - name: Multi-line bash
+        run: |
+          echo "I will fail"
+          exit 1
+
       - name: Say goodbie
         run: echo "Goodbye!"
